// ════════════════════════════════════════════════════════════════════
// BandSync — play.html entry point
// ════════════════════════════════════════════════════════════════════
// Mini-SPA with 4 states: song-select → setup → game → results.
// Phase 1 (now): auth gate + song-select pulling from songs/manifest.json.
// Phases 2-4 land setup, gameplay (reusing 2player.html engine), results.
// ════════════════════════════════════════════════════════════════════

import { getUser } from './services/auth.js';

const stateEl      = document.getElementById('state');
const stateLabelEl = document.getElementById('state-label');

const ctx = {
  user:     null,
  manifest: null,
  song:     null,   // selected song from manifest
};

// ── BOOT ───────────────────────────────────────────────────────────

init().catch(err => {
  console.error('play.js: startup error', err);
  renderError('STARTUP ERROR', err.message);
});

async function init() {
  // Auth gate — Supabase persists the session in localStorage across loads.
  const user = await getUser();
  if (!user) {
    location.href = 'index.html';
    return;
  }
  ctx.user = user;

  // Load song library manifest (generated by tools/build-songs.mjs).
  try {
    const res = await fetch('songs/manifest.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    ctx.manifest = await res.json();
  } catch (err) {
    renderError('COULD NOT LOAD LIBRARY',
      `Failed to fetch songs/manifest.json — ${err.message}.\n` +
      `If you just pulled, regenerate with:  node tools/build-songs.mjs`);
    return;
  }

  // Handle ?invite=<id> for play invites — for now, just stash it for setup.
  const invite = new URLSearchParams(location.search).get('invite');
  if (invite) ctx.inviteId = invite;

  renderSongSelect();
}

// ── STATE: SONG SELECT ─────────────────────────────────────────────

function renderSongSelect() {
  setStateLabel('SONG SELECT');

  const songs = ctx.manifest.songs ?? [];
  if (!songs.length) {
    renderError('NO SONGS', 'The library is empty. Run: node tools/build-songs.mjs');
    return;
  }

  stateEl.innerHTML = `
    <div class="state-inner">
      <div class="section-label">LIBRARY — ${songs.length} SONGS</div>
      <div class="song-grid">
        ${songs.map(songCard).join('')}
      </div>
    </div>
  `;

  stateEl.querySelectorAll('[data-song-file]').forEach(el => {
    el.addEventListener('click', () => {
      const file = el.dataset.songFile;
      ctx.song = songs.find(s => s.file === file);
      renderSetupPlaceholder();   // phase 2 lands the real setup
    });
  });
}

function songCard(song) {
  const trackCount = song.tracks.length;
  const duet       = trackCount > 1 ? '<span class="badge-duet">DUET</span>' : '';
  const trackList  = song.tracks.map(t => t.name).join(' + ');
  const mm         = Math.floor(song.durationSec / 60);
  const ss         = String(Math.round(song.durationSec % 60)).padStart(2, '0');

  return `
    <button class="song-card" data-song-file="${esc(song.file)}">
      <div class="song-title">${esc(song.title)}${duet}</div>
      <div class="song-tracks">${esc(trackList)}</div>
      <div class="song-meta">
        <span class="pill">${song.bpm} BPM</span>
        <span class="pill">${mm}:${ss}</span>
        <span class="pill">${trackCount} TRACK${trackCount === 1 ? '' : 'S'}</span>
      </div>
    </button>
  `;
}

// ── STATE: SETUP (placeholder for phase 2) ─────────────────────────

function renderSetupPlaceholder() {
  setStateLabel('SETUP');
  const trackList = ctx.song.tracks.map(t => `• ${esc(t.name)}`).join('<br>');
  stateEl.innerHTML = `
    <div class="state-inner">
      <div class="center-msg">
        <div class="title">SETUP — COMING NEXT</div>
        <div style="font-size:14px;color:#fff;margin-top:8px">${esc(ctx.song.title)}</div>
        <div style="color:var(--dim);font-size:11px;letter-spacing:1.5px">
          ${ctx.song.bpm} BPM · ${ctx.song.tracks.length} track${ctx.song.tracks.length === 1 ? '' : 's'}
        </div>
        <div style="font-size:11px;color:var(--purple2);margin-top:8px;line-height:1.7">
          ${trackList}
        </div>
        <button onclick="history.back()" style="
          margin-top:24px;padding:8px 20px;background:transparent;
          border:0.5px solid var(--border2);color:var(--dim);border-radius:6px;
          font-size:10px;letter-spacing:2px;font-family:inherit">
          ← PICK ANOTHER SONG
        </button>
      </div>
    </div>
  `;
  stateEl.querySelector('button').addEventListener('click', e => {
    e.preventDefault();
    renderSongSelect();
  });
}

// ── HELPERS ────────────────────────────────────────────────────────

function setStateLabel(text) {
  stateLabelEl.textContent = text;
}

function renderError(title, message) {
  setStateLabel('');
  stateEl.innerHTML = `
    <div class="center-msg error">
      <div class="title">${esc(title)}</div>
      <pre>${esc(message)}</pre>
    </div>
  `;
}

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
