-- ═══════════════════════════════════════════════════════════════════
-- BandSync — Migration 0001: Player Identity & Multi-Account Sessions
-- ═══════════════════════════════════════════════════════════════════
-- Adds the three tables that back DESIGN.md §26:
--
--   device_codes        — 6-digit handoff codes for the friend-attach flow
--   play_sessions       — one row per completed song
--   play_session_slots  — per-player results within a session
--
-- Plus claim_device_code() — a SECURITY DEFINER function that's the
-- only way to redeem a code, so the device_codes table can be kept
-- private (no enumeration risk from a wide-open SELECT policy).
--
-- HOW TO RUN (existing project):
--   Supabase dashboard → SQL editor → paste this file → Run.
--
-- For a fresh BandSync project, just run supabase/schema.sql instead
-- — it contains everything in this migration plus the original tables.
-- ═══════════════════════════════════════════════════════════════════


-- ── DEVICE CODES ──────────────────────────────────────────────────
-- Short-lived 6-digit codes generated by a friend on their own device
-- and redeemed by a host to attach the friend's identity to a player
-- slot. Single-use, 10-minute TTL. See DESIGN.md §26.
create table public.device_codes (
  code           text primary key,                -- 6 digits, e.g. '742619'
  user_id        uuid references auth.users on delete cascade not null,
  display_name   text,                            -- profile snapshot at generation —
  avatar         text,                            -- the host's UI shows the friend's
  accent_color   text,                            -- identity instantly after claim
  created_at     timestamptz default now(),
  expires_at     timestamptz not null,
  used_at        timestamptz,
  used_by_user   uuid references auth.users on delete set null
);

create index device_codes_user_idx    on public.device_codes (user_id, created_at desc);
create index device_codes_expires_idx on public.device_codes (expires_at);

alter table public.device_codes enable row level security;

-- The owner can manage their own codes (list, revoke).
-- No general SELECT policy — codes are read through claim_device_code()
-- below, which prevents enumeration of live codes by random callers.
create policy "dc_insert_own" on public.device_codes
  for insert with check (auth.uid() = user_id);

create policy "dc_select_own" on public.device_codes
  for select using (auth.uid() = user_id);

create policy "dc_update_own" on public.device_codes
  for update using (auth.uid() = user_id);

create policy "dc_delete_own" on public.device_codes
  for delete using (auth.uid() = user_id);


-- ── claim_device_code(p_code) ─────────────────────────────────────
-- The ONLY way a non-owner can interact with a device_codes row.
-- SECURITY DEFINER so it bypasses the (deliberately strict) RLS, but
-- only returns data for valid, unexpired, unused codes — and marks the
-- row consumed atomically so a code can only be claimed once even
-- under concurrent attempts.
--
-- Returns the friend's profile snapshot for the host's UI. Returns no
-- rows if the code is bad/expired/already used (caller treats as "invalid").
create or replace function public.claim_device_code(p_code text)
returns table (
  user_id      uuid,
  display_name text,
  avatar       text,
  accent_color text
)
language plpgsql security definer
set search_path = public
as $$
declare
  v_row public.device_codes%rowtype;
begin
  -- Caller must be authenticated. (Anon claims would be meaningless —
  -- we wouldn't know who's claiming, so couldn't record used_by_user.)
  if auth.uid() is null then
    return;
  end if;

  -- Lock the candidate row to serialize concurrent claim attempts.
  select * into v_row
  from public.device_codes
  where code = p_code
    and used_at is null
    and expires_at > now()
  for update;

  if not found then
    return;
  end if;

  update public.device_codes
    set used_at = now(),
        used_by_user = auth.uid()
    where code = p_code;

  return query
    select v_row.user_id, v_row.display_name, v_row.avatar, v_row.accent_color;
end;
$$;

grant execute on function public.claim_device_code(text) to authenticated;


-- ── PLAY SESSIONS ─────────────────────────────────────────────────
-- One row per song played, regardless of player count. Slots (below)
-- hold the per-player results.
create table public.play_sessions (
  id                uuid default gen_random_uuid() primary key,
  host_user_id      uuid references auth.users on delete set null,
  song_file         text not null,                -- 'twinkle-twinkle.mid'
  song_title        text not null,
  started_at        timestamptz default now(),
  ended_at          timestamptz,
  speed_level       int,
  hit_window_level  int,
  player_count      int not null check (player_count between 1 and 4)
);

create index play_sessions_host_idx on public.play_sessions (host_user_id, started_at desc);


-- ── PLAY SESSION SLOTS ────────────────────────────────────────────
-- One row per player per session. user_id is null for guests; set for
-- host / friend identities. Indexed by user_id so a friend's "show my
-- history" query is a direct lookup even across sessions they didn't host.
create table public.play_session_slots (
  session_id    uuid references public.play_sessions on delete cascade not null,
  slot          int not null check (slot between 1 and 4),
  identity      text not null check (identity in ('host','friend','guest')),
  user_id       uuid references auth.users on delete set null,
  display_name  text not null,
  instrument    text not null check (instrument in ('piano','drums')),
  track_index   int not null,
  track_name    text,
  score         int default 0,
  accuracy      int,
  grade         text,
  perfect       int default 0,
  good          int default 0,
  miss          int default 0,
  wrong         int default 0,
  max_combo     int default 0,
  primary key (session_id, slot)
);

create index play_session_slots_user_idx on public.play_session_slots (user_id);


-- ── RLS — play_sessions ───────────────────────────────────────────
alter table public.play_sessions enable row level security;

create policy "ps_insert_host" on public.play_sessions
  for insert with check (auth.uid() = host_user_id);

-- Host of the session can read it…
create policy "ps_select_host" on public.play_sessions
  for select using (auth.uid() = host_user_id);

-- …and any user who appears in a slot can read it (their own history).
create policy "ps_select_participant" on public.play_sessions
  for select using (
    exists (
      select 1 from public.play_session_slots ss
      where ss.session_id = play_sessions.id
        and ss.user_id    = auth.uid()
    )
  );

-- Host can set ended_at, etc.
create policy "ps_update_host" on public.play_sessions
  for update using (auth.uid() = host_user_id);


-- ── RLS — play_session_slots ──────────────────────────────────────
alter table public.play_session_slots enable row level security;

-- Insert / update slots only inside a session you host. The host can
-- write rows for any user_id (host / friend / null guest) — that's the
-- whole point of the design — but the blast radius is bounded to
-- session rows they themselves created.
create policy "pss_insert_host" on public.play_session_slots
  for insert with check (
    exists (
      select 1 from public.play_sessions s
      where s.id           = play_session_slots.session_id
        and s.host_user_id = auth.uid()
    )
  );

create policy "pss_update_host" on public.play_session_slots
  for update using (
    exists (
      select 1 from public.play_sessions s
      where s.id           = play_session_slots.session_id
        and s.host_user_id = auth.uid()
    )
  );

-- Read your own slots (your history view)…
create policy "pss_select_own" on public.play_session_slots
  for select using (auth.uid() = user_id);

-- …or any slot inside a session you hosted.
create policy "pss_select_host" on public.play_session_slots
  for select using (
    exists (
      select 1 from public.play_sessions s
      where s.id           = play_session_slots.session_id
        and s.host_user_id = auth.uid()
    )
  );


-- ═══════════════════════════════════════════════════════════════════
-- Done. Verify in the SQL editor:
--   select * from public.device_codes;        -- empty, but no error
--   select * from public.play_sessions;
--   select * from public.play_session_slots;
--   select public.claim_device_code('000000');  -- returns no rows
-- ═══════════════════════════════════════════════════════════════════
